baseURL: https://johanbasson.net

languageCode: en-us
title: "Johan Basson Profile and Blog"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  background: "images/site/background.jpg"
  # GitHub repo URL of your site
  gitRepo: https://github.com/hugo-toha/hugo-toha.github.io

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: false

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  features:
    analytics:
      enabled: true
      goatCounter:
        code: johanbasson
      counterDev:
        id: johangwbasson@gmail.com
      google:
        id: UA-122321624-2